name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_luas.py
      id: test_luas-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 3
        setup-command: ''
    - name: test_isipadu.py
      id: test_isipadu-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 2
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_LUAS-PY_RESULTS: "${{steps.test_luas-py.outputs.result}}"
        TEST_ISIPADU-PY_RESULTS: "${{steps.test_isipadu-py.outputs.result}}"
      with:
        runners: test_luas-py,test_isipadu-py
